### ISSUE TITLE
look at Action Tracker plugin for possible use in CMSC 355

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow-study#13]

**Comment by Zerthick** [comment]
Action Tracker appears to log simple key stroke events.  Sample log attached.
[IntelliJ_IDEA_action_tracker_28_07_2017__11_02.txt](https://github.com/vcu-swim-lab/stack-intheflow-study/files/1183435/IntelliJ_IDEA_action_tracker_28_07_2017__11_02.txt)

**Comment by damevski** [comment]
Activity tracker seems better

https://plugins.jetbrains.com/plugin/8126-activity-tracker
